name: Douyin Bond Maintainer

on:
  schedule:
    - cron: '0 5 * * *'  # 每天 UTC 5:00，即北京时间 13:00
  workflow_dispatch:      # 允许手动触发

jobs:
  bond:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium

      - name: Store cookies into file
        run: echo "${{ secrets.COOKIES }}" > cookies.json

      - name: Set environment variables
        run: |
          echo "NICKNAME=${{ secrets.NICKNAME }}" >> $GITHUB_ENV
          echo "MSG=${{ secrets.MSG }}" >> $GITHUB_ENV

      - name: Run Douyin Bond Maintainer
        run: python main.py

      - name: Upload error screenshot
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshot
          path: error.png
