name: Douyin Bond Maintainer

on:
  schedule:
    - cron: '0 5 * * *'  # 每天 UTC 5:00，即北京时间 13:00
  workflow_dispatch:      # 允许手动触发

jobs:
  bond:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium

      - name: Download and configure V2Ray
        run: |
          # 下载并解压 V2Ray
          curl -LO https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip
          unzip v2ray-linux-64.zip -d v2ray
          
          # 解码并生成 config.json
          echo "${{ secrets.V2RAY_CONFIG }}" | base64 --decode > v2ray/config.json

      - name: Run V2Ray
        run: |
          # 使用正确的命令启动 V2Ray
          nohup ./v2ray/v2ray run -config ./v2ray/config.json &

      - name: Store cookies into file
        run: echo "${{ secrets.COOKIES }}" > cookies.json

      - name: Set environment variables
        run: |
          echo "NICKNAME=${{ secrets.NICKNAME }}" >> $GITHUB_ENV
          echo "MSG=${{ secrets.MSG }}" >> $GITHUB_ENV

      - name: Run Douyin Bond Maintainer
        run: |
          # 设置代理环境变量
          export http_proxy=socks5h://127.0.0.1:10808
          export https_proxy=socks5h://127.0.0.1:10808
          python main.py

      - name: Upload error screenshot
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshot
          path: error.png
